### ISSUE TITLE
Feature: Phrases and Regular Expressions

### ISSUE THREAD

**Issue by shellscape** [dessant/reaction-comments#1]
Phenomenal bot. I'd love to be able to provide a list of phrases or regular expressions that the bot also looked for.

**Comment by dessant** [comment]
This sounds like a great idea, but for a separate bot where you could have a list of regular expressions that trigger different actions, such as editing or deleting the comment, labeling the issue, and so on. I may create such an action at some point, but I don't expect to have time for it in the near future.
